### ISSUE TITLE
Access token gets lost / security.user returns irrelevant data

### ISSUE THREAD

**Issue by mbeckenbach** [JustMaier/angular-spa-security#6]
First: Great work! Thanks! your provider saved me from a lot of headache‎.

When logging in with or without remember me, the object security.user contains the returned values from the server: 

``` json
{"access_token":"XXX-LOOONG-XXX","token_type":"bearer","expires_in":1209599,"userName":"admin",".issued":"Tue, 11 Feb 2014 20:18:28 GMT",".expires":"Tue, 25 Feb 2014 20:18:28 GMT"}
```

Perfect, thats excactly what i want to know about the user from a security aspect. :+1:  

But, when you refresh the browser / open a new window security.user contains: 

``` json
{"UserName":"admin","Email":"admin@test.de","IsConfirmed":false,"HasRegistered":true,"LoginProvider":null}
```

The only interesting thing here from a security aspect is UserName. :-1: This will not help much for future api calls when a user has ticked rememberme or a browser refresh is made. (Internet Explorers "security" warnings that all the time....! And some users too.)

As a small workarround i have modified your initialize function to have at least the access token.

``` javascript:
Api.getUserInfo(accessToken()).success(function (user) {
                    Security.user = user;
                    Security.user.access_token = accessToken();
                    if (securityProvider.events.reloadUser) securityProvider.events.reloadUser(Security, user); // Your Register events
                });
```

Maybe you should store all the infos from the /token response into session / local storage and return those here instead of the user info object.

Merging userinfo with the security related infos would not be a good idea in my opinion. In my case this would be arround 40 properties. Maybe you can simply copy your code into a new method? security.getUserInfo()?

**Comment by masimplo** [comment]
Security.user should contain values returned by /userinfo. The token is return by /token. /login creates a different type of security.user. I think this is incorrect for consistency reasons, so maybe this should be reviewed. The access token is correctly persisted to the local storage and retrieved when a new window/refresh happens. Everything having to do with the token should be taken care of inside this module (it even puts the beared in $http) so I do not see the reason why you would want the token inside the security.user object.

**Comment by mbeckenbach** [comment]
Maybe i was to unclear what my idea behind this point is. Or maybe i get something totaly wrong with the concept of bearer tokens. 

Imagine you are building a bigger spa with dozens of factories doing api calls to your asp.net web api. You dont want to check session / local storage on your own. You want ro rely on your security provider and dont think about it. So when doing a new api call and setting up the http header you simply access $scope.$root.security.user.access_token and have it right where you need it. 

Now let's imagine someone out there invents the ultimate replacement for the session storage / local storage API and it becomes depricated. I dont want to update all my fectories where i am accessing that token info from storage and make sure its supported in all browsers. I want to update my security provider. Nothing else. 

The other aspect of seperating the /token return data from the userinfo data is: Because it has totaly different semantic meaning and the way it is now could now have a big performance impact in some scenarios.

AND: Maybe i need to now when the token will be expired? I do not get that information after refreshing the browser. This can be a very important info in some cases and is not returned by userinfo. (Auto logout after expiration for example.)

Lets take my spa app as an example. My /api/account/userinfo will return about 40 properties. Some can take a while because i do some strange magic in my account controller like reading some files and merging data from different databases. First: I do not need the userinfo (which is kind of a user profile) right after login. To be excact i need it after opening a specific view. So why should i load all the data, cause that much traffic without needing the userinfo? Every bit of traffic cost much money. In some hosting providers (azure) and the user who is accessing over 3g while traveling through another country for example.

The default asp.net web api account controller seperates those data for the same reason, i think. /account gives security related info. /api/account/userinfo gives me a userprofile which maybe is not relevant in a security matter. (Except you include roles or claims or something like that here - maybe you shouldnt do that)

So my suggestion was to create something where the programmer of a spa could retrieve something that in any controller or factory:

$scope.$root.security.user returns:

``` json
 {"access_token":"XXX-LOOONG-XXX","token_type":"bearer","expires_in":1209599,"userName":"admin",".issued":"Tue, 11 Feb 2014 20:18:28 GMT",".expires":"Tue, 25 Feb 2014 20:18:28 GMT"}
```

$scope.$root.security.getUserInfo() returns:

``` json
{"UserName":"admin","Email":"admin@test.de", LastBreakfast: "Eggs", "HasGirlfriend": false}
```

**Comment by masimplo** [comment]
I see what you mean and you have a valid point since you are using getUserInfo to get the whole user profile rather than just the necessary information to "personalize" the spa experience. The problem still remains that whatever security.user gets should be consistent throughout the security module and currently it is not, since it get data from the /login and data from /getuserinfo depending on the flow. 

That being said, you do not use to access the security service to any place making http or rest requests to the backend. As you probably noticed, after access_token is set, the $http default bearer is set to that token. 

Lastly your point about the token life is valid, but I find it much more preferable for the backend to reject an expired token rather than checking it every time it is used in the frontend. 

Of course you are free to implement your SPA whichever way you like, I am just saying that I have used this module in my SPA with minor modifications (main ones being, security.user always gets populated by userinfo and security.user returns a promise instead of a value)

**Comment by mbeckenbach** [comment]
Ok. I also see what you mean. :-) Makes sense. Maybe i should create a getUserProfile method at my api.

**Comment by JustMaier** [comment]
Hey guys, looks like there has already been some good conversation on this topic.

The module is structured the way it is to work with the standard / out-of the-box MVC5 account controller. I agree with @mxa055 that since /login and /userinfo return different objects, the values in Security.user aren't consistent. However, I see this as a back-end issue (a problem with the standard template) that can be resolved in the account controller by changing the values that it returns from the different methods.

@mbeckenbach I think you found the correct solution. Rather than fetching 40+ properties that will delay login, just return the essentials with /getUserInfo and fetch extras with another API call. Since the token is added to all http requests after login, you don't need to worry about including the token in any future API requests.
